# Generated by Django 6.0.5 on 2026-07-08 20:18

import beauty_formula.apps.core.validators.image_validator
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do serviço')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do serviço')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração do serviço')),
                ('image', models.ImageField(default='default/service_img.jpg', upload_to='services/', validators=[beauty_formula.apps.core.validators.image_validator.validate_image_file], verbose_name='Imagem do serviço')),
                ('total_bookings', models.PositiveIntegerField(default=0, editable=False, help_text='Número total de vezes que este serviço foi agendado', verbose_name='Total de agendamentos')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=70, help_text='Percentual de comissão para o funcionário (70 = padrão do sistema)', max_digits=5, verbose_name='Comissão (%)')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='services_se_name_32d28c_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_service_name')],
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(verbose_name='Horário agendado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('no_show', 'Não compareceu')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('price_at_booking', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço no momento do agendamento')),
                ('duration_at_booking', models.DurationField(editable=False, verbose_name='Duração no momento do agendamento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('canceled_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do cancelamento')),
                ('rated_at', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em')),
                ('is_active', models.BooleanField(default=True, help_text='Desative em vez de deletar para não quebrar agendamentos antigos.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_schedulings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedulings', to='accounts.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedulings', to='accounts.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedulings', to='services.service')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('lunch', 'Almoço'), ('break', 'Pausa'), ('personal', 'Pessoal'), ('medical', 'Médico'), ('day_off', 'Folga'), ('vacation', 'Férias'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da semana')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Início')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Início')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Bloqueio de horário',
                'verbose_name_plural': 'Bloqueios de horário',
                'indexes': [models.Index(fields=['employee', 'weekday'], name='services_em_employe_2c95f7_idx'), models.Index(fields=['employee', 'start_datetime'], name='services_em_employe_a82fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Fim')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='accounts.employee')),
            ],
            options={
                'verbose_name': 'Horário de trabalho',
                'verbose_name_plural': 'Horários de trabalho',
                'ordering': ['employee', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['employee', 'weekday'], name='services_em_employe_f51f01_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'weekday', 'start_time'), name='unique_employee_weekday_start')],
            },
        ),
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Avaliação média do serviço, calculada com base nas avaliações dos clientes.', max_digits=3, verbose_name='Avaliação média')),
                ('total_reviews', models.PositiveIntegerField(default=0, editable=False, help_text='Número total de avaliações recebidas para este serviço.', verbose_name='Total de avaliações')),
                ('total_rating', models.PositiveIntegerField(default=0, editable=False, help_text='Soma de todas as avaliações recebidas para este serviço, usada para calcular a avaliação média.', verbose_name='Soma das avaliações')),
                ('comments', models.TextField(blank=True, default='', help_text='Comentários dos clientes sobre o serviço.', null=True, verbose_name='Comentários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='average_ratings_scheduling', to='services.scheduling')),
            ],
            options={
                'verbose_name': 'Avaliação média',
                'verbose_name_plural': 'Avaliações médias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scheduling'], name='services_av_schedul_1048b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('scheduling',), name='unique_average_rating_per_scheduling')],
            },
        ),
        migrations.AddIndex(
            model_name='scheduling',
            index=models.Index(fields=['service'], name='services_sc_service_203e34_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduling',
            index=models.Index(fields=['client'], name='services_sc_client__f3bd11_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduling',
            index=models.Index(fields=['employee'], name='services_sc_employe_dd4e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduling',
            index=models.Index(fields=['scheduled_time'], name='services_sc_schedul_4b2132_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduling',
            index=models.Index(fields=['status'], name='services_sc_status_c199ad_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduling',
            index=models.Index(fields=['status', 'scheduled_time'], name='services_sc_status_843422_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduling',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('canceled_at__isnull', False), ('status__in', ['canceled', 'no_show'])), models.Q(models.Q(('status__in', ['canceled', 'no_show']), _negated=True), ('canceled_at__isnull', True)), _connector='OR')), name='canceled_status_requires_canceled_at'),
        ),
    ]
