# Generated by Django 6.0.5 on 2026-08-06 20:44

import beauty_formula.apps.core.validators.image_validator
import beauty_formula.apps.website.models.product_models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('subject', models.TextField(choices=[('appointment', 'Agendamento'), ('question', 'Dúvida'), ('compliment', 'Elogio'), ('complaint', 'Reclamação'), ('other', 'Outro')], default='other', verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.TextField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('resolved', 'Resolvido'), ('archived', 'Arquivado')], default='pending', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='website_con_full_na_e78ea8_idx'), models.Index(fields=['status'], name='website_con_status_1dc9a3_idx'), models.Index(fields=['created_at'], name='website_con_created_b36bc0_idx'), models.Index(fields=['email'], name='website_con_email_a16188_idx')],
                'constraints': [models.UniqueConstraint(fields=('full_name',), name='unique_contact_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O preço não pode ser negativo')], verbose_name='Preço do produto')),
                ('image', models.ImageField(blank=True, default='default/product_img.png', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=beauty_formula.apps.website.models.product_models.product_image_path, validators=[beauty_formula.apps.core.validators.image_validator.validate_image_file], verbose_name='Imagem do produto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='O estoque não pode ser negativo')], verbose_name='Estoque do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='website_pro_name_4cb352_idx'), models.Index(fields=['price'], name='website_pro_price_ba0a94_idx'), models.Index(fields=['is_active'], name='website_pro_is_acti_87ded3_idx'), models.Index(fields=['stock'], name='website_pro_stock_8b56fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_product_name')],
            },
        ),
    ]
