# Generated by Django 6.0.5 on 2026-08-10 13:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0013_alter_averagerating_is_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_payment_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID da cobrança no Asaas')),
                ('asaas_customer_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do cliente no Asaas')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Serviço')),
                ('billing_type', models.CharField(choices=[('UNDEFINED', 'Indefinido'), ('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito')], db_index=True, default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido'), ('CONFIRMED', 'Confirmado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado'), ('RECEIVED_IN_CASH', 'Recebido em dinheiro'), ('REFUND_REQUESTED', 'Reembolso solicitado'), ('REFUND_IN_PROGRESS', 'Reembolso em andamento'), ('CHARGEBACK_REQUESTED', 'Chargeback solicitado'), ('CHARGEBACK_DISPUTE', 'Disputa de chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Aguardando reversão de chargeback'), ('DUNNING_REQUESTED', 'Negativação solicitada'), ('DUNNING_RECEIVED', 'Negativação recebida'), ('AWAITING_RISK_ANALYSIS', 'Em análise antifraude'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=30, verbose_name='Status do Pagamento')),
                ('due_date', models.DateField(verbose_name='Data limite para efetuar pagamento')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição da cobrança')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Referência externa')),
                ('invoice_url', models.URLField(blank=True, null=True, verbose_name='URL da fatura')),
                ('bank_slip_url', models.URLField(blank=True, null=True, verbose_name='URL do boleto')),
                ('pix_qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code Pix')),
                ('pix_copy_paste', models.TextField(blank=True, null=True, verbose_name='Código Pix copia e cola')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor líquido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('synced_with_asaas', models.BooleanField(default=False, verbose_name='Sincronizado com Asaas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_client', to='accounts.client')),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_scheduling', to='services.scheduling')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='payment_pay_status_f5a552_idx'), models.Index(fields=['client', 'status'], name='payment_pay_client__8e935b_idx')],
            },
        ),
    ]
