# Generated by Django 6.0.5 on 2026-08-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('services', '0014_alter_scheduling_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='scheduling',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payments_scheduling', to='services.scheduling'),
        ),
    ]
