# Generated by Django 6.0.5 on 2026-08-19 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_asaas_customer_id'),
        ('payment', '0002_alter_payment_scheduling'),
        ('services', '0016_scheduling_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da comissão')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga'), ('canceled', 'Cancelada')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.employee', verbose_name='Funcionário')),
                ('scheduling', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='services.scheduling', verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='commission_employee_status_idx'), models.Index(fields=['status', 'created_at'], name='commission_status_created_idx')],
            },
        ),
    ]
