# Generated by Django 6.0.5 on 2026-08-24 03:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_booking_window_days'),
        ('payment', '0003_employeecommission'),
        ('services', '0017_scheduling_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecommission',
            name='competencia',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Competência (mês de referência)'),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='competencia_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Competência ajustada em'),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='competencia_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_competencia_changes', to=settings.AUTH_USER_MODEL, verbose_name='Competência ajustada por'),
        ),
        migrations.AddField(
            model_name='employeecommission',
            name='competencia_original',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Competência original (calculada)'),
        ),
        migrations.AddIndex(
            model_name='employeecommission',
            index=models.Index(fields=['employee', 'competencia'], name='commission_emp_competencia_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecommission',
            index=models.Index(fields=['competencia', 'status'], name='comm_competencia_status_idx'),
        ),
    ]
