# Generated by Django 6.0.5 on 2026-08-25 13:46

from django.db import migrations


def backfill_competencia(apps, schema_editor):
    EmployeeCommission = apps.get_model("payment", "EmployeeCommission")
    db_alias = schema_editor.connection.alias

    commissions = (
        EmployeeCommission.objects.using(db_alias)
        .filter(competencia_changed_at__isnull=True)
        .select_related("scheduling")
    )

    to_update = []
    for commission in commissions:
        from django.utils import timezone

        scheduled_time = commission.scheduling.scheduled_time
        local_dt = timezone.localtime(scheduled_time) if timezone.is_aware(scheduled_time) else scheduled_time
        reference_month = local_dt.date().replace(day=1)

        if commission.competencia != reference_month:
            commission.competencia = reference_month
            commission.competencia_original = reference_month
            to_update.append(commission)

    if to_update:
        EmployeeCommission.objects.using(db_alias).bulk_update(
            to_update, ["competencia", "competencia_original"]
        )


def noop_reverse(apps, schema_editor):
    """Não dá pra reverter com segurança — o valor anterior era só o default da 0004, sem valor de negócio."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_employeecommission_competencia_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_competencia, noop_reverse),
    ]