# Generated by Django 6.0.5 on 2026-09-03 16:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sessionmetadata'),
        ('payment', '0005_backfill_competencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='', verbose_name='Motivo do cancelamento')),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor original')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taxa de cancelamento (%)')),
                ('fee_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor retido (taxa)')),
                ('refund_value', models.DecimalField(decimal_places=2, help_text='original_value - fee_value. É o valor que o admin manda pra Asaas ao aprovar.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor a devolver')),
                ('status', models.CharField(choices=[('pending', 'Aguardando análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Observações do admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analisado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='accounts.client', verbose_name='Cliente')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payment.payment', verbose_name='Pagamento')),
                ('requested_by', models.ForeignKey(help_text='Quem cancelou o agendamento que originou o pedido — cliente, funcionário ou admin.', on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Analisado por')),
            ],
            options={
                'verbose_name': 'Pedido de reembolso',
                'verbose_name_plural': 'Pedidos de reembolso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_ref_status_671fb0_idx'), models.Index(fields=['client', 'status'], name='payment_ref_client__98dffc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('payment',), name='one_pending_refund_request_per_payment'), models.CheckConstraint(condition=models.Q(('refund_value__lte', models.F('original_value'))), name='refund_value_lte_original_value')],
            },
        ),
    ]
