[pytest]
DJANGO_SETTINGS_MODULE = beauty_formula.config.settings.dev
python_files = test_*.py *_test.py
testpaths = beauty_formula/apps
addopts = -v --tb=short --strict-markers -p no:warnings
markers =
    django_db: Marks tests that use the database
    slow: Marks tests as slow