# Generated by Django 6.0.5 on 2026-09-07 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('scheduling_complete', 'Agendamento concluído'), ('scheduling_confirmed', 'Agendamento confirmado'), ('scheduling_cancelled', 'Agendamento cancelado'), ('scheduling_rescheduled', 'Agendamento remarcado'), ('scheduling_reminder', 'Lembrete de agendamento'), ('payment_received', 'Pagamento recebido'), ('refund_requested', 'Reembolso solicitado'), ('refund_reviewed', 'Reembolso avaliado'), ('request_rating', 'Solicitação para avaliação'), ('new_rating', 'Nova avaliação recebida'), ('employee_promoted', 'Funcionário promovido'), ('system', 'Aviso do sistema')], max_length=32, verbose_name='Tipo')),
                ('title', models.CharField(max_length=140, verbose_name='Título')),
                ('body', models.CharField(blank=True, max_length=280, verbose_name='Mensagem')),
                ('action_url', models.CharField(blank=True, max_length=300, verbose_name='URL de ação')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('actor', models.ForeignKey(blank=True, help_text='Quem originou o evento (ex: funcionário que cancelou), se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Autor do evento')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
