# Generated by Django 6.0.5 on 2026-09-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('scheduling_complete', 'Agendamento concluído'), ('scheduling_confirmed', 'Agendamento confirmado'), ('scheduling_cancelled', 'Agendamento cancelado'), ('scheduling_rescheduled', 'Agendamento remarcado'), ('scheduling_reminder', 'Lembrete de agendamento'), ('scheduling_no_show', 'Não comparecimento'), ('payment_received', 'Pagamento recebido'), ('refund_requested', 'Reembolso solicitado'), ('refund_reviewed', 'Reembolso avaliado'), ('request_rating', 'Solicitação para avaliação'), ('new_rating', 'Nova avaliação recebida'), ('employee_promoted', 'Funcionário promovido'), ('profile_incomplete', 'Perfil incompleto'), ('system', 'Aviso do sistema')], max_length=32, verbose_name='Tipo'),
        ),
    ]
