# Generated by Django 6.0.5 on 2026-07-21 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_assignments', to='accounts.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='services.service')),
            ],
            options={
                'verbose_name': 'Serviço por Funcionário',
                'verbose_name_plural': 'Serviços por Funcionários',
                'ordering': ['employee', 'service'],
                'indexes': [models.Index(fields=['employee', 'service'], name='services_em_employe_cd5664_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'service'), name='unique_employee_service')],
            },
        ),
    ]
