# Generated by Django 6.0.5 on 2026-07-21 23:59

import beauty_formula.apps.core.validators.image_validator
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_employeeservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60), message='A duração deve ser de pelo menos 1 minuto')], verbose_name='Duração do serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='default/service_img.png', upload_to='services/', validators=[beauty_formula.apps.core.validators.image_validator.validate_image_file], verbose_name='Imagem do serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O preço não pode ser negativo')], verbose_name='Preço do serviço'),
        ),
    ]
