# Generated by Django 6.0.5 on 2026-07-23 14:32

import beauty_formula.apps.core.validators.image_validator
import beauty_formula.apps.services.models.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='default/service_img.png', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=beauty_formula.apps.services.models.service.service_image_path, validators=[beauty_formula.apps.core.validators.image_validator.validate_image_file], verbose_name='Imagem do serviço'),
        ),
    ]
