# Generated by Django 6.0.5 on 2026-07-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeservice',
            old_name='active',
            new_name='is_active',
        ),
    ]
