# Generated by Django 6.0.5 on 2026-07-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0006_rename_active_employeeservice_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeservice',
            index=models.Index(fields=['employee', 'is_active'], name='services_em_employe_11c873_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeservice',
            index=models.Index(fields=['service', 'is_active'], name='services_em_service_3e536b_idx'),
        ),
    ]
