# Generated by Django 6.0.5 on 2026-07-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_employeeservice_services_em_employe_11c873_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimeoff',
            name='block_modality',
            field=models.CharField(choices=[('recurring', 'Bloqueio Recorrente'), ('punctual', 'Bloqueio Pontual')], default='recurring', max_length=20, verbose_name='Modalidade do Bloqueio'),
        ),
        migrations.AddField(
            model_name='employeetimeoff',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Usado pela expiração automática de bloqueios pontuais: a task do Celery marca como False (soft delete) 1 minuto após end_datetime, em vez de excluir o registro.', verbose_name='Ativo'),
        ),
    ]
