# Generated by Django 6.0.5 on 2026-07-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0008_employeetimeoff_block_modality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_schedulings', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_schedulings', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_schedulings', to='services.service'),
        ),
    ]
