# Generated by Django 6.0.5 on 2026-07-29 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_scheduling_client_alter_scheduling_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='rescheduled_to',
            field=models.OneToOneField(blank=True, help_text='Novo agendamento criado a partir do reagendamento deste registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from', to='services.scheduling', verbose_name='Reagendado para'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('no_show', 'Não compareceu'), ('rescheduled', 'Reagendado')], db_index=True, default='confirmed', max_length=20, verbose_name='Status'),
        ),
    ]
