# Generated by Django 6.0.5 on 2026-08-05 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0010_scheduling_rescheduled_to_alter_scheduling_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAverageRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Avaliação média')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total de avaliações')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Média de avaliação do funcionário',
                'verbose_name_plural': 'Médias de avaliação dos funcionários',
            },
        ),
        migrations.CreateModel(
            name='ServiceAverageRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Avaliação média')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total de avaliações')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Média de avaliação do serviço',
                'verbose_name_plural': 'Médias de avaliação dos serviços',
            },
        ),
        migrations.AlterModelOptions(
            name='averagerating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avaliação de serviço', 'verbose_name_plural': 'Avaliações de serviços'},
        ),
        migrations.RemoveConstraint(
            model_name='averagerating',
            name='unique_average_rating_per_scheduling',
        ),
        migrations.RemoveIndex(
            model_name='averagerating',
            name='services_av_schedul_1048b8_idx',
        ),
        migrations.AddField(
            model_name='averagerating',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_ratings', to='accounts.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='comment',
            field=models.TextField(blank=True, help_text='Deixe um comentário sobre sua experiência', max_length=500, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_ratings', to='accounts.employee', verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Altorizado'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '⭐ 1 Estrela - Péssimo'), (2, '⭐⭐ 2 Estrelas - Ruim'), (3, '⭐⭐⭐ 3 Estrelas - Regular'), (4, '⭐⭐⭐⭐ 4 Estrelas - Bom'), (5, '⭐⭐⭐⭐⭐ 5 Estrelas - Excelente')], help_text='Nota de 1 a 5 estrelas', null=True, verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='averagerating',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_ratings', to='services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='scheduling',
            field=models.OneToOneField(help_text='Agendamento concluído que originou esta avaliação.', on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='services.scheduling', verbose_name='Agendamento'),
        ),
        migrations.AddIndex(
            model_name='averagerating',
            index=models.Index(fields=['employee'], name='services_av_employe_8087e1_idx'),
        ),
        migrations.AddIndex(
            model_name='averagerating',
            index=models.Index(fields=['service'], name='services_av_service_547580_idx'),
        ),
        migrations.AddIndex(
            model_name='averagerating',
            index=models.Index(fields=['client'], name='services_av_client__bc1f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='averagerating',
            index=models.Index(fields=['rating'], name='services_av_rating_d16d39_idx'),
        ),
        migrations.AddField(
            model_name='employeeaveragerating',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_rating', to='accounts.employee', verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='serviceaveragerating',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='average_rating', to='services.service', verbose_name='Serviço'),
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='total_rating',
        ),
        migrations.RemoveField(
            model_name='averagerating',
            name='total_reviews',
        ),
    ]
