# Generated by Django 6.0.5 on 2026-08-05 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0011_employeeaveragerating_serviceaveragerating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_ratings', to='accounts.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_ratings', to='accounts.employee', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ 1 Estrela - Péssimo'), (2, '⭐⭐ 2 Estrelas - Ruim'), (3, '⭐⭐⭐ 3 Estrelas - Regular'), (4, '⭐⭐⭐⭐ 4 Estrelas - Bom'), (5, '⭐⭐⭐⭐⭐ 5 Estrelas - Excelente')], help_text='Nota de 1 a 5 estrelas', verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='averagerating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_ratings', to='services.service', verbose_name='Serviço'),
        ),
    ]
