# Generated by Django 6.0.5 on 2026-08-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_averagerating_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Autorizado'),
        ),
    ]
