# Generated by Django 6.0.5 on 2026-08-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
        ('services', '0013_alter_averagerating_is_authorized'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='averagerating',
            constraint=models.UniqueConstraint(fields=('client', 'service', 'employee'), name='unique_rating_per_client_service_employee'),
        ),
    ]
