# Generated by Django 6.0.5 on 2026-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_averagerating_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('created', 'Criado'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('no_show', 'Não compareceu'), ('rescheduled', 'Reagendado')], db_index=True, default='created', max_length=20, verbose_name='Status'),
        ),
    ]
