# Generated by Django 6.0.5 on 2026-08-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_scheduling_status'),
        ('services', '0014_averagerating_unique_rating_per_client_service_employee'),
    ]

    operations = [
    ]
