# Generated by Django 6.0.5 on 2026-08-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_merge_20260817_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lembrete enviado em'),
        ),
    ]
