# Generated by Django 6.0.5 on 2026-08-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_scheduling_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Momento exato em que o status virou COMPLETED. Diferente de `updated_at` (que muda a qualquer edição), este campo só é preenchido uma vez, dentro de complete() — é a base usada pra calcular a competência (mês) da comissão gerada a partir daqui.', null=True, verbose_name='Concluído em'),
        ),
    ]
