# Generated by Django 6.0.5 on 2026-08-31 19:36

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('appointments_by_status', models.JSONField(default=dict, help_text='Ex.: {"completed": 42, "canceled": 3, "rescheduled": 1, ...}', verbose_name='Agendamentos por status')),
                ('total_appointments', models.PositiveIntegerField(default=0, verbose_name='Total de agendamentos no mês')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma do valor dos atendimentos CONCLUÍDOS no mês.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor total arrecadado')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soma de todas as comissões geradas com competência neste mês, pagas ou não.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor total em comissões')),
                ('total_commissions_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comissões já pagas')),
                ('total_commissions_pending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comissões pendentes')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total arrecadado − valor total em comissões.', max_digits=12, verbose_name='Lucro líquido')),
                ('employee_breakdown', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Lista por funcionário no mês: id, nome, total de atendimentos concluídos, faturamento gerado, comissão total/paga/pendente. Ex.: [{"employee_id": "...", "employee_name": "...", "completed_appointments": 12, "revenue": "600.00", "commission_total": "120.00", "commission_paid": "100.00", "commission_pending": "20.00"}, ...]', verbose_name='Balanço por funcionário')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Gerado/atualizado em')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_report_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Balanço mensal',
                'verbose_name_plural': 'Balanços mensais',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='monthly_report_year_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_monthly_report_snapshot')],
            },
        ),
    ]
