# Generated by Django 6.0.5 on 2026-09-01 00:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportsnapshot',
            name='service_breakdown',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Lista por serviço no mês: id, nome, quantidade de atendimentos concluídos e percentual sobre o total. Ex.: [{"service_id": "...", "service_name": "...", "completed_appointments": 8, "percentage": "33.33"}, ...]', verbose_name='Atendimentos por serviço'),
        ),
    ]
