# Generated by Django 6.0.5 on 2026-07-08 20:18

import beauty_formula.apps.accounts.models.client
import beauty_formula.apps.accounts.models.employee
import beauty_formula.apps.core.validators.image_validator
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nome de usuário')),
                ('phone', models.CharField(blank=True, help_text='Número de telefone do funcionário.', max_length=20, null=True, verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('bio', models.TextField(blank=True, help_text='Breve descrição sobre o funcionário.', null=True, verbose_name='Biografia')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Prefiro não informar')], default='O', max_length=10, verbose_name='Gênero')),
                ('instagram', models.URLField(blank=True, help_text='URL do perfil do Instagram do funcionário.', max_length=255, null=True, verbose_name='Instagram')),
                ('photo', models.ImageField(blank=True, default='default/employee_img.jpeg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=beauty_formula.apps.accounts.models.employee.employee_photo_path, validators=[beauty_formula.apps.core.validators.image_validator.validate_image_file])),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador Root'), ('client', 'Cliente'), ('employee', 'Funcionário')], default='client', max_length=20, verbose_name='Tipo de usuário')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('is_trusty', models.BooleanField(default=False, verbose_name='Confiável?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de admissão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nome de usuário')),
                ('phone', models.CharField(blank=True, help_text='Número de telefone do cliente.', max_length=20, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Prefiro não informar')], default='O', max_length=10, verbose_name='Gênero')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('instagram', models.URLField(blank=True, help_text='URL do perfil do Instagram do cliente.', max_length=255, null=True, verbose_name='Instagram')),
                ('photo', models.ImageField(blank=True, default='default/client_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=beauty_formula.apps.accounts.models.client.client_photo_path, validators=[beauty_formula.apps.core.validators.image_validator.validate_image_file])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
