# Generated by Django 6.0.5 on 2026-07-08 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', to='services.service'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_cl_first_n_7eb737_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_em_first_n_97f1fc_idx'),
        ),
    ]
