# Generated by Django 6.0.5 on 2026-07-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='services',
        ),
    ]
