# Generated by Django 6.0.5 on 2026-07-17 20:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employee_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Número de telefone no formato internacional, ex: +55 11 99999-8888.', max_length=128, null=True, region='BR'),
        ),
    ]
