# Generated by Django 6.0.5 on 2026-08-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_client_gender_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='asaas_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do cliente na Asaas'),
        ),
    ]
