# Generated by Django 6.0.5 on 2026-08-24 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_asaas_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='booking_window_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Quantos dias à frente a agenda deste funcionário fica aberta pra clientes agendarem. Substitui o valor global padrão (30 dias) quando definido individualmente.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Janela de agendamento (dias)'),
        ),
    ]
