# Generated by Django 6.0.5 on 2026-08-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_booking_window_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='JTI do token')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Metadado de sessão',
                'verbose_name_plural': 'Metadados de sessão',
            },
        ),
    ]
